### ISSUE TITLE
Administrative rationalization

### ISSUE THREAD

**Issue by patwater** [codeforamerica/Mission-Vision-and-Operating-Principles#14]
Key need to not just build a shiny digital layer but also do the hard work of reforming obsolete administrative structures.  See here for a concrete example in So Cal: https://medium.com/a-r-g-o/the-unique-civic-data-opportunity-in-southern-california-272a0ec48f53

**Comment by ZoeBlumenfeld** [comment]
Yes, @patwater! Use the principles and practices of the digital age to not only change how governments deliver services, but also to change how they operate.
